### ISSUE TITLE
MinidumpHeaderSignatureMismatchException: EGAP

### ISSUE THREAD

**Issue by demberto** [skelsec/minidump#14]
This occured when I tried to parse the minidump I copied after BSOD caused by running Nox App Player. Guranteed unmodified. OS: Win 10 64-bit _(minidump-0.0.13)_. **Directly copied** from `C:/Windows/Minidump`
[minidump.zip](https://github.com/skelsec/minidump/files/4429644/minidump.zip)

**Comment by skelsec** [comment]
Hello! The problem is that the file you submitted is in a different format than what this project is for.
This project supports the **minidump** file format as specified by Microsoft [here](https://docs.microsoft.com/en-us/windows/win32/api/minidumpapiset/)
Your file is a **crash dump** which is kinda specified [here](https://github.com/volatilityfoundation/volatility/wiki/Crash-Address-Space#64-bit-crash-dumps). I'd recommend using Volatility or Rekall to parse your file.  
As for the confusion: you can thank Microsoft for the naming inconsistencies :)

**Comment by demberto** [comment]
I understand, btw my Nox player app issue was solved by running their DG readiness tool.
